### PR TITLE
Attempt to fix wrong orders of quotation foreground colors

### LINKED ISSUE #1132: Code Quotations Foreground Highlighting
Code Quotations should only change the background color of the spans they encompass. The foreground coloring for all of the expressions inside
the quotation should remain visible.

@vasily-kirichenko  I uninstalled VFPT before taking this screenshot.
[Reinstalled VFPT using this build](https://ci.appveyor.com/project/dungpa/visualfsharppowertools/build/2.1.0-a1509301808)

```
    type Condition (expr: Expr<bool>) =
        member __.Expr = expr

    let (|AAA|_|) _ = Some ()
    let func x y = x + y
    let x = <@ Condition <@ 3435 > 243 @> , "some string", 
                typeof<bool> ,(|AAA|_|) () , 22::[] ,
                [| 22.0, 2234.0 |], func 2 5 , (+) 10 13, 
                "operator" = "red?" , @"string" 
            @>
```

### PR DESCRIPTION
**Pull request by dungpa**
Fix #1132.

### CODE REVIEW

**Comment by dungpa** [comment]
@cloudRoutine I can't reproduce the error here. Could you please check this build to see whether it's fixed?

**Comment by vasily-kirichenko** [comment]
Seems to work OK in VS 2015:

image

**Comment by dungpa** [comment]
I took a detailed look at coloring of active patterns usage. It's very tricky so I opened a separate issue at #1137.

This PR can be merged after rebasing.

**Comment by vasily-kirichenko** [comment]
Will you rebase it?

**Comment by dungpa** [comment]
Done.

**Comment by vasily-kirichenko** [comment]
Great.

**Pull request merged**
