### PR TITLE
FCS 1.4.0.4 breaking changes

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
It compiles, but it's no way the right solution. Suggestions? /cc @dsyme

### CODE REVIEW

**Comment by dungpa** [comment]
@vasily-kirichenko According to https://github.com/fsharp/FSharp.Compiler.Service/pull/412/files, the removed internals have been added back to other places. Could you try to use them?

**Comment by dsyme** [comment]
If you need anything else exposed (e.g. more token types) please just submit a PR, thanks.  (Selectively making things public improves our ability to evolve the FCS API)

**Comment by vasily-kirichenko** [comment]
As https://github.com/fsharp/FSharp.Compiler.Service/pull/417 merged and new FCS NuGet package is pablished, we need to update `paket.lock` and this PR is ready.

**Comment by dungpa** [comment]
@vasily-kirichenko Please add Ignore attributes to formatting tests. They fail because Fantomas is currently incompatible with new FCS.

I'll fix the incompatibility issue in a few days.

**Comment by vasily-kirichenko** [comment]
Done.

**Pull request merged**
