### PR TITLE
Nunit 3

### PR DESCRIPTION
**Pull request by vasily-kirichenko**

### CODE REVIEW

**Comment by dungpa** [comment]
I don't know why but a few VS unit tests keep failing. Do they pass locally on your machine?

**Comment by vasily-kirichenko** [comment]
Nope. I'm just too frustrated to fix them now. Waiting until I'm OK to deal with all the mock stuff.

**Comment by vasily-kirichenko** [comment]
We were missing events in `DocumentEventListener` (there may be some between our `Async.AwaitEvent ...`s as far as I understand). Now it's impossible, but a couple of tests fail on CI, but all are green locally.

**Comment by vasily-kirichenko** [comment]
OMG it's green.

**Comment by dungpa** [comment]
Great jobs. You even fix a long-standing bug :).

**Comment by vasily-kirichenko** [comment]
Yeah. As a benefit, now I understand how `DocumentEventListener` works ;)

**Pull request merged**
