### PR TITLE
Require Admin privileges while saving navigation bar configuration

### LINKED ISSUE #37: Navigation bar not showing
After i installed the extension, and restarted i could see the navigation bar.
After another restart of IDE, navigation bar disappeared forever...
Any ideas?

### PR DESCRIPTION
**Pull request by dungpa**
Fix #37.

@jaredpar Is there any way to turn on UAC or escalate permissions inside VS process? If yes, we might have better UI interaction than displaying an error message.

### CODE REVIEW

**Comment by xperiandri** [comment]
What does mean that Navigation Bar requires admin privileges?
Do I have to run VS with Admin Privileges once I want to enable it and that is enough?
Is there any explanation somewhere?

**Comment by dungpa** [comment]
> Do I have to run VS with Admin Privileges once I want to enable it and that is enough?

Yes, that's enough.

> Is there any explanation somewhere?

http://tomasp.net/blog/regions-navigation.aspx/

**Comment by xperiandri** [comment]
So why not to disable that option until Visual Studio is running with admin privileges?
I mean set enabled to combobox to false

**Comment by dungpa** [comment]
Yes, that's better. Care to send a PR?

The whole logic is handled at https://github.com/fsprojects/VisualFSharpPowerTools/blob/b9373f46eddc2f5bfffde86d0df0748c7ef7fd27/src/FSharpVSPowerTools/GeneralOptionsPage.cs#L63-L78.

**Comment by xperiandri** [comment]
Yes, I will

**Comment by xperiandri** [comment]
How to make this if page will look like property page?
I mean that change that we want to implement.

**Comment by dungpa** [comment]
What do you mean?

We replace `GeneralOptionsControl` by a wholly new control. `GeneralOptionsPage` should not change at all.
As long as you keep all public properties https://github.com/fsprojects/VisualFSharpPowerTools/blob/b9373f46eddc2f5bfffde86d0df0748c7ef7fd27/src/FSharpVSPowerTools/GeneralOptionsControl.cs#L15-L138 intact, the original behaviour is preserved.

**Comment by xperiandri** [comment]
I mean how to disable an item in property grid for NavBar if not admin

**Pull request merged**
