### PR TITLE
Added doc page for lint

### PR DESCRIPTION
**Pull request by duckmatt**
Added a brief page with some screenshots on using the linter. Also fixed a bug where pressing the delete key on a hint would try to cast the selected hints to a string list (they used to be strings, but are now `Hint` records)

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
Generating docs fails on my machine:
```
Generating 'D:\git\VisualFSharpPowerTools\docs\tools\..\content/codeformatting.html'
System.MethodAccessException: Attempt by method 'FSharpVSPowerTools.Lexer.|GenericTypeParameterPrefix|StaticallyResolvedTypeParameterPrefix|Other|@92(System.String, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpTokenInfo)' to access method 'Microsoft.FSharp.Compiler.Parser.tokenTagToTokenId(Int32)' failed.
   at FSharp.CodeFormat.CodeFormatAgent.ParseSource(String file, String source, FSharpOption`1 options, FSharpOption`1 defines) in c:\Tomas\Public\tpetricek\FSharp.Formatting\src\FSharp.CodeFormat\CodeFormatAgent.fs:line 390
   at FSharp.Literate.ParseScript.parseScriptFile(String file, String content, CompilerContext ctx) in c:\Tomas\Public\tpetricek\FSharp.Formatting\src\FSharp.Literate\ParseScript.fs:line 198
   at FSharp.Literate.Literate.ParseScriptFile[d](String path, FSharpOption`1 formatAgent, FSharpOption`1 compilerOptions, FSharpOption`1 definedSymbols, FSharpOption`1 references, FSharpOption`1 fsiEvaluator) in c:\Tomas\Public\tpetricek\FSharp.Formatting\src\FSharp.Literate\Main.fs:line 67
   at FSharp.Literate.Literate.ProcessScriptFile(String input, FSharpOption`1 templateFile, FSharpOption`1 output, FSharpOption`1 format, FSharpOption`1 formatAgent, FSharpOption`1 prefix, FSharpOption`1 compilerOptions, FSharpOption`1 lineNumbers, FSharpOption`1 references, FSharpOption`1 fsiEvaluator, FSharpOption`1 replacements, FSharpOption`1 includeSource, FSharpOption`1 layoutRoots, FSharpOption`1 generateAnchors, FSharpOption`1 assemblyReferences, FSharpOption`1 customizeDocument) in c:\Tomas\Public\tpetricek\FSharp.Formatting\src\FSharp.Literate\Main.fs:line 167
   at <StartupCode$FSharp-Literate>.$Main.processScriptFile@184.Invoke(String file, String output) in c:\Tomas\Public\tpetricek\FSharp.Formatting\src\FSharp.Literate\Main.fs:line 184
   at <StartupCode$FSharp-Literate>.$Main.processDirectory@199(FSharpOption`1 format, Boolean processRecursive, FSharpFunc`2 processScriptFile, FSharpFunc`2 processMarkdown, String indir, String outdir) in c:\Tomas\Public\tpetricek\FSharp.Formatting\src\FSharp.Literate\Main.fs:line 218
   at FSharp.Literate.Literate.ProcessDirectory(String inputDirectory, FSharpOption`1 templateFile, FSharpOption`1 outputDirectory, FSharpOption`1 format, FSharpOption`1 formatAgent, FSharpOption`1 prefix, FSharpOption`1 compilerOptions, FSharpOption`1 lineNumbers, FSharpOption`1 references, FSharpOption`1 fsiEvaluator, FSharpOption`1 replacements, FSharpOption`1 includeSource, FSharpOption`1 layoutRoots, FSharpOption`1 generateAnchors, FSharpOption`1 assemblyReferences, FSharpOption`1 processRecursive, FSharpOption`1 customizeDocument) in c:\Tomas\Public\tpetricek\FSharp.Formatting\src\FSharp.Literate\Main.fs:line 181
   at FSI_0003.buildDocumentation() in D:\git\VisualFSharpPowerTools\docs\tools\generate.fsx:line 84
   at <StartupCode$FSI_0003>.$FSI_0003.main@() in D:\git\VisualFSharpPowerTools\docs\tools\generate.fsx:line 93
```
because `Microsoft.FSharp.Compiler.Parser.tokenTagToTokenId` has been made internal in the latest FCS version.

**Comment by dungpa** [comment]
@forki Could you help initial migration to Paket dependencies group? We get conflicting assemblies more and more often. Thanks.

**Comment by vasily-kirichenko** [comment]
Great idea, just was thinking about it :)

**Comment by forki** [comment]
Sure. I actually created groups to solve this concrete issue.

**Comment by forki** [comment]
Can you remember the reason you pinned fsharp.core?

**Comment by vasily-kirichenko** [comment]
No idea. Try to unpin it.

**Comment by forki** [comment]
https://github.com/fsprojects/VisualFSharpPowerTools/pull/1149

**Comment by vasily-kirichenko** [comment]
I rebased it on master and pushed changes directly.

**Pull request closed without merging**
