### PR TITLE
Use reflection to get source location when FCS doesn't give enough information

### PR DESCRIPTION
**Pull request by dungpa**
Partial fix for #947 (NOT YET READY).

For Octokit NuGet package, FCS returns faulty ranges (no range or a dummy range with wrong information). We try to use Reflection to recover source locations. I'm not sure it's a good approach; any other idea is appreciated.

@ctaggart It seems `pdbReader.GetMethod` doesn't work correctly for any overriden/abstract member e.g. any symbol from this line:

    let a = github.Activity.Events.GetAll()

Is this a SourceLink's bug? Any idea?

### CODE REVIEW

**Comment by dungpa** [comment]
@ctaggart I need your help with this one to move forward. Should I wait for changes in SourceLink or discard this PR as we don't support source-indexed C# assemblies at this point?

**Comment by ctaggart** [comment]
As I just mentioned in ctaggart/SourceLink#63, not all files or methods gets indexed by the compilers. F12 at design time will only work with concrete methods that get source indexed, not any of the interfaces.

**Comment by dungpa** [comment]
That sounds really limiting. On a related note, can signature files (*.fsi) be source indexed?

**Comment by dungpa** [comment]
Closing this PR until there is more versatile support for pdb files from SourceLink.

**Comment by ctaggart** [comment]
I believe Portable PDBs https://github.com/ctaggart/SourceLink/issues/93 will solve several of the issues here. I'll create a new issue here.

**Pull request closed without merging**
