### PR TITLE
fix bugs in SyntaxConstructClassifier

### PR DESCRIPTION
**Pull request by vasily-kirichenko**

### CODE REVIEW

**Comment by dungpa** [comment]
Which bugs?

**Comment by vasily-kirichenko** [comment]
`maybe` in Slow stage can short circuits before it reset `IsUpdating` flag, which causes Slow stage stop working for a document. Fixed here https://github.com/fsprojects/VisualFSharpPowerTools/pull/1231/files#diff-25504538e85b6dd9767544225eb1d9bcR324

`haveFirstAndLastSpansNotChanged` has flipped logic, fixed here https://github.com/fsprojects/VisualFSharpPowerTools/pull/1231/files#diff-25504538e85b6dd9767544225eb1d9bcL224

**Comment by dungpa** [comment]
Can you take a look at the failing test https://github.com/fsprojects/VisualFSharpPowerTools/blob/55ae98097ddc2a95e417ca2368662e6563dbbcb8/tests/FSharpVSPowerTools.Tests/SyntaxConstructClassifierTests.fs#L106-L136? Something is wrong with ordering of categories.

**Comment by vasily-kirichenko** [comment]
Fixed.

**Pull request merged**
