### PR TITLE
WIP: Put dependencies in groups

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by forki** [comment]
One test gets a time out. Any ideas?

**Comment by vasily-kirichenko** [comment]
That one is timed out in 50% of times. I re-run the build.

**Comment by vasily-kirichenko** [comment]
Ah, that's another one. We should pin FAKE to the old version because the freshest one is not SourceLink-ed.

**Comment by vasily-kirichenko** [comment]
Thanks a lot, it's great!

**Comment by dungpa** [comment]
@forki How did you do migration? Modify `dependencies` file and run `paket install`? It's not entirely clear from Paket docs http://fsprojects.github.io/Paket/groups.html

**Comment by forki** [comment]
yes. install tries to detect what changed in the deps file and comes up with minimal changes in lock file.

**Comment by dungpa** [comment]
Got it. Thanks.

**Pull request merged**
