### PR TITLE
Use forward slashes in FSI generated references

### LINKED ISSUE #1093: Generated references could use forward slashes as path seperators
When generating references for FSI:

```
#I __SOURCE_DIRECTORY__
#r @"..\..\..\src\bin\Debug\FunSharp.Library.dll"
#r @"System.Core.dll"
#r @"System.dll"
#r @"System.Numerics.dll"
#r @"..\..\..\lib\Xwt.dll"
#r @"..\..\..\lib\Xwt.Gtk.dll"
```

Backslashes don't work on non-windows platforms, whereas Windows can handle forward slashes.
Would like to be able to use the generated files on OSX without manually replacing the slashes ;)

### PR DESCRIPTION
**Pull request by dedale**
Close #1093

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
Cool.

I think we should remove `@` leading symbol everywhere.

**Comment by dedale** [comment]
I removed `@` and amended commit. I don't understand appveyor failure :confused:

**Comment by dungpa** [comment]
@dedale I rebuilt the PR on AppVeyor CI. It should be fine now.

**Comment by vasily-kirichenko** [comment]
Shouldn't we remove `@` chars from here https://github.com/dedale/VisualFSharpPowerTools/blob/master/src/FSharpVSPowerTools.Logic/FsiReferenceCommand.fs#L92 as well?

**Comment by vasily-kirichenko** [comment]
And from here https://github.com/dedale/VisualFSharpPowerTools/blob/master/src/FSharpVSPowerTools.Logic/FsiReferenceCommand.fs#L147

**Comment by dedale** [comment]
Oh sorry.
Do you think it is possible to add unit tests for this command? I'm not sure how to proceed.

**Comment by dungpa** [comment]
We don't have tests for this command because it needs mocks of many Visual studio interfaces, which is non-trivial.

If you would like to test the changes, the VSIX is available from CI https://ci.appveyor.com/project/dungpa/visualfsharppowertools/build/2.1.0-a1508301850/artifacts

Moreover, the guide for testing locally is here https://github.com/fsprojects/VisualFSharpPowerTools/blob/master/CONTRIBUTING.md#how-is-the-code-base-organized

**Comment by dedale** [comment]
Thanks @dungpa. Actually, I did test manually the first version of the PR. I already pushed the removal of three `@`. Going to test this manually now.

**Comment by dungpa** [comment]
@dedale Thanks for your help.

**Comment by dedale** [comment]
You're both welcome! Glad to help :)

**Pull request merged**
