### PR TITLE
Fsharp vsix

### PR DESCRIPTION
**Pull request by cloudRoutine**
This isn't intended to be merged. as it's still a WIP.  I've been caught up in another project, so I wanted to open this up so we could discuss the process of moving more of the codebase to F#, streamlining the rest and paying off some technical debt. 

The main tasks remaining that I'd like to accomplish are -
* Making FsXaml GUIs for all the dialog pages
* Switch to using the settings store for persistent configuration settings
* Stop using services to provide options settings
* Upgrade to using newer services over DTE calls
* Switch to VS services over redundant VFPT implementations

### CODE REVIEW

**Comment by dungpa** [comment]
Thanks for the great work. We may not be able to accept everything. But there are a few good enhancements I would like to pull in through separate PRs:

1. Put all files of Logic projects into their own folders.
2. Use importing constructors in Logic.VS2013 and Logic.VS2015 projects.
3. Add convenient extension methods for ServiceProvider.

**Comment by cloudRoutine** [comment]
In many of these cases we can move away from using the service provider by using an importing constructor instead.

**Comment by dungpa** [comment]
@cloudRoutine Would you mind to submit the above bullet points as separate PRs? There may be more things we can pull, but it's much easier to do piece by piece. Thanks.

**Comment by cloudRoutine** [comment]
no problem, I'll try to get to it later today or tomorrow.

**Comment by cloudRoutine** [comment]
The file reorganization has been a total disaster, somehow I introduced a bunch of bugs I can't track down. I'll start over from scratch later today

**Comment by dungpa** [comment]
@cloudRoutine How is it going? I think the main idea is to copy relevant changes from this PR and apply to current master :-).

**Pull request closed without merging**
