### PR TITLE
Add a new option for interface member identifiers

### PR DESCRIPTION
**Pull request by dungpa**
UserVoice request: http://vfpt.uservoice.com/forums/247560-general/suggestions/8557105-allow-renaming-of-self-reference-for-implementing

Again I flex my "great" UI skills. Any suggestion is welcome.

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
If the identifier is empty, then the result is as following:

image

**Comment by dungpa** [comment]
Ok, invalid identifiers are now disallowed.

**Comment by dungpa** [comment]
Test failures are fixed separately in #1031.

**Comment by vasily-kirichenko** [comment]
```fsharp
class ==> ``class`` (ok)
``class`` ==> ``class`` (ok)
``->`` ==> ``->`` (ok)
-> ==> validation error (ok)
(empty string) ==> no validation error, same behavior as before
x y ==> validation error (should be ``x y``)
```

**Comment by dungpa** [comment]
Ok, done.

**Comment by vasily-kirichenko** [comment]
Great. As a (arguably useful) side effect we got to know that the following compiles :)

image

**Pull request merged**
