### PR TITLE
Fcs 2.0.0.8

### PR DESCRIPTION
**Pull request by vasily-kirichenko**

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
@dungpa any ideas why the tests fail?

**Comment by dungpa** [comment]
I think it's due to breaking changes in FCS. Probably Fantomas and FSharpLint should be updated to the last version as well @duckmatt.

**Comment by dsyme** [comment]
Let me know if I can help work this out

**Comment by vasily-kirichenko** [comment]
https://github.com/dungpa/fantomas/pull/195

@dungpa please release new nuget package so we can proceed with this

**Comment by dungpa** [comment]
Done https://www.nuget.org/packages/Fantomas/2.1.0. Thanks.

**Comment by vasily-kirichenko** [comment]
Thanks, the Fantomas tests pass. Waiting for a new FsLint.

**Comment by duckmatt** [comment]
Updated fsharplint: https://www.nuget.org/packages/FSharpLint.Core/0.0.16

**Comment by vasily-kirichenko** [comment]
Thanks guys, it's finally green :)

**Pull request merged**
