### PR TITLE
Life easier for polyglot / C# / ES6 -developer to code F#

### PR DESCRIPTION
**Pull request by Thorium**
Some easy common typos are replaced while you write:
var to let,
C#/ES6 lambda to F#-lambda

### CODE REVIEW

**Comment by Thorium** [comment]
Just try it. No need to break your flow when you accidentally write
```
var x = 3
```
to new empty line. Or if you accidentally forgot to write F#-style lambda after coding a lot of C# or ES6.

**Comment by Thorium** [comment]
Hmm. I wonder if this is too naïve implementation for the lambda: F#-compiler-service is not used. So there could be cases that have custom operator (a <=> b) or you could have C#/JS-code in some kind of multi-line-string to convert it to something and then this could be just a little annoyance. You can enable/disable this from the project menu, but should the default be on or off... I think there are more newbies and non-primary-F# programmers than meta programmers.

**Comment by vasily-kirichenko** [comment]
I think it should not be a part of VFPT since:

1. It's a very general feature. The same results one can easily achieve with an external system-wide tools like http://www.autohotkey.com/. 
2. It's not needed after you've been writing F# for at least a week.

Sorry, we have to reject this PR. If you want to help the project, you may take a look at https://github.com/fsprojects/VisualFSharpPowerTools/pull/902 which have severe performance issues and is not feature complete. 

For the future, please, discuss features/fixes in advance with @dungpa and me. Thanks.

**Comment by Thorium** [comment]
Ok, no problem! :-)

**Comment by dungpa** [comment]
@Thorium Sorry that it didn't work out for the first time. You're welcome to send bug fixes or implement feature requests from http://vfpt.uservoice.com/forums/247560-general/filters/top. However, due to nature of tooling development, it requires some discussion before proceeding.

**Pull request closed without merging**
