### PR TITLE
Fix formatting bugs

### LINKED ISSUE #1143: formatting code with duck typing results in unnecessary parentheses
This:
```fsharp
let f (arg : 'T) = (^T : (member Value : string) arg)
```
after `CTRL+K,F` becomes this:
```fsharp
let f (arg : 'T) = ((^T : (member Value : string) arg))
```

### LINKED ISSUE #1151: Formatting code changes 'default val' and 'override val' to 'member val'
This:
```fsharp
type Entity() = 
    abstract Id : int with get, set
    default val Id = 0 with get, set
```
and this:
```fsharp
type Entity() = 
    abstract Id : int with get, set
    override val Id = 0 with get, set
```
becomes this (and cannot be compiled):
```fsharp
type Entity() = 
    abstract Id : int with get, set
    member val Id = 0 with get, set
```
I think this is a very rarely used language feature though.

### LINKED ISSUE #1194: Syntax highlighting does not work in 2013 now
On the screenshot you can see a sample code that contains a lot of syntax elements that should have been coloured:

image

I'm using the following version of the extension:

image

And here is why I think the colorization should be on:

image

And here is why I think the colors in settings do not work:

image

### LINKED ISSUE #1265: format code will Add redundant parentheses
my code:
    type TernaryExp = 
        
        static member Ternary(value, truePast : 't, falsePast : 't Lazy) = 
            if value then truePast
            else falsePast.Value
        
        static member Ternary(value, truePast : 't, falsePast : 't) = 
            if value then truePast
            else falsePast
    
    let inline ternaryExpHelper< ^t, ^a, ^b when (^t or ^b) : (static member Ternary : bool * ^a * ^b -> ^a)> v (a, b) = 
        ((^t or ^b) : (static member Ternary : bool * ^a * ^b -> ^a) (v, a, b))

Bug found in last line，once I format the code , it add a pair of redundant parentheses,format more, add more

### PR DESCRIPTION
**Pull request by dungpa**
Close #1265.
Close #1194.
Close #1151.
Close #1143.

This requires a very big change. I need help to verify whether the feature still works.

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
It does disaster results on `UriUtils.fs` from FSharp.Data.

**Comment by vasily-kirichenko** [comment]
`UriInfo` type appears two times and field definition section appears detached one more time.

**Comment by vasily-kirichenko** [comment]
`StructuralInference.fs`: validation failed

**Comment by vasily-kirichenko** [comment]
`CsvRuntime.fs`: 
```fsharp
  /// Saves CSV to a string
    member x.Save(/// Returns a new csv with the same rows as the original but which guarantees
                  /// that each row will be only be read and parsed from the input at most once.
                  /// Returns a new csv containing only the rows for which the given predicate returns "true".
                  path : string, [<Optional>] /// Returns a new csv with only the first N rows of the underlying csv.
                                              /// Returns a csv that, when iterated, yields rowswhile the given predicate
                                              /// returns <c>true</c>, and then returns no further rows.
                                              /// Returns a csv that skips N rows and then yields the remaining rows.
                                              /// Returns a csv that, when iterated, skips rows while the given predicate returns
                                              /// <c>true</c>, and then yields the remaining rows.
                                              /// Returns a csv that when enumerated returns at most N rows.
                                              ?separator, [<Optional>] ?quote) = 
        let writer = new StreamWriter(File.OpenWrite(path))
        x.Save(writer, ?separator = separator, ?quote = quote)
```

**Comment by vasily-kirichenko** [comment]
Formatting one of the files throws:

image


```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
The following exception occurs inside async blocks: System.NullReferenceException: Object reference not set to an instance of an object.

   at Microsoft.VisualStudio.Text.Operations.Implementation.BeforeTextBufferChangeUndoPrimitive.GetMap(ITextView view)
   at Microsoft.VisualStudio.Text.Operations.Implementation.AfterTextBufferChangeUndoPrimitive.Create(ITextView textView, ITextUndoHistory undoHistory)
   at Microsoft.VisualStudio.Text.Operations.Implementation.EditorOperations.AddAfterTextBufferChangePrimitive()
   at <StartupCode$FSharpVSPowerTools-Logic>.$CodeFormattingCommands.ExecuteFormat@69-3.Invoke(Boolean _arg3) in D:\github\FSharpVSPowerTools\src\FSharpVSPowerTools.Logic\CodeFormattingCommands.fs:line 72
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@787-1.Invoke(a a)
   at FSharpVSPowerTools.ProjectSystem.VSUtils.comp@403-7.Invoke(String arg00) in D:\github\FSharpVSPowerTools\src\FSharpVSPowerTools.Logic\VSUtils.fs:line 403
   at FSharpVSPowerTools.ProjectSystem.VSUtils.comp@400-6.Invoke(Exception _arg2) in D:\github\FSharpVSPowerTools\src\FSharpVSPowerTools.Logic\VSUtils.fs:line 403
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@803.Invoke(AsyncParams`1 args)
   at <StartupCode$FSharp-Core>.$Control.loop@425-40(Trampoline this, FSharpFunc`2 action)
   at Microsoft.FSharp.Control.Trampoline.ExecuteAction(FSharpFunc`2 firstAction)
   at Microsoft.FSharp.Control.TrampolineHolder.Protect(FSharpFunc`2 firstAction)
   at <StartupCode$FSharp-Core>.$Control.-ctor@510-1.Invoke(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by dungpa** [comment]
I tried to fix the debug assertion. The other parts are not meant to be fixed in this PR (The feature easily fails on F# code with non-XmlDoc comments.)

**Pull request merged**
