### PR TITLE
Enable some of features in Peek Definition view

### PR DESCRIPTION
**Pull request by vasily-kirichenko**

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
It's ready.

**Comment by dungpa** [comment]
Can you fix VS unit tests? Most of them are failing and the builds timed out.

**Comment by vasily-kirichenko** [comment]
`ITextBuffer.GetSnapshotPoint` returns None:

image

I cannot see how it's related to this PR changes :(

**Comment by dungpa** [comment]
A number of tests are timed out because `ProjectItem.DTE` doesn't have a mock implementation yet. GetSnapshotPoint use the mock IText* classes at https://github.com/fsprojects/VisualFSharpPowerTools/blob/master/tests/TestUtilities/Mocks

**Comment by vasily-kirichenko** [comment]
Cannot believe my eyes, the tests pass. An accident ¯\_(ツ)_/¯

**Comment by dungpa** [comment]
What lines fix the issue here?

**Comment by vasily-kirichenko** [comment]
This https://github.com/vasily-kirichenko/FSharpVSPowerTools/commit/e26e719605cf1310ba6f9cbe39423a24295023c1#diff-90073b99ebc6d47f9cc9f32fc54b098eL13 and this https://github.com/vasily-kirichenko/FSharpVSPowerTools/commit/e26e719605cf1310ba6f9cbe39423a24295023c1#diff-44faceb41341c443713f89dd1468b8aeL125

**Comment by vasily-kirichenko** [comment]
I've made it editable, as C# one, it's pretty useful. Now I think it should support all our features.

**Comment by vasily-kirichenko** [comment]
OK, I'll add Depth Colorized for now.

**Comment by vasily-kirichenko** [comment]
Wow, it was a bad idea 
image

**Comment by vasily-kirichenko** [comment]
Let's leave at for the future.

**Comment by dungpa** [comment]
So what features are supported in Peek Definition view? Can we peek into a Peek Definition view?

**Comment by vasily-kirichenko** [comment]
Outlining, Highlight refs/printfs, coloring.

**Pull request merged**
