### PR TITLE
Remove logic vs2013 project

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
**It's based on https://github.com/fsprojects/VisualFSharpPowerTools/pull/1296, so it should be merged first, or you can just merge this one and forget about #1296**

### CODE REVIEW

**Comment by dungpa** [comment]
Could you rebase so that the diff is easier to read?

**Comment by vasily-kirichenko** [comment]
Done

**Comment by dungpa** [comment]
That warm feeling when we make things better by deleting code :-).

**Comment by vasily-kirichenko** [comment]
:)

**Pull request merged**
