### PR TITLE
Fsc 5.0.0

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
It's based on https://github.com/fsprojects/VisualFSharpPowerTools/pull/1400

### CODE REVIEW

**Comment by dungpa** [comment]
How did you force FSharp.Core NuGet package? Did you have to remove GAC FSharp.Core references first?

**Comment by vasily-kirichenko** [comment]
@dungpa yes, I removed GAC references by hand. I always do just that at work :(

**Comment by vasily-kirichenko** [comment]
So this PR will fail until FsLint and Fantomas update to FCS 5.0.0

**Comment by vasily-kirichenko** [comment]
It seems FAKE and Selenium and Newtonsoft.Json are terrible changed after update :(

**Comment by vasily-kirichenko** [comment]
Everything OK except Fantomas tests.

**Comment by dungpa** [comment]
I updated the NuGet package https://www.nuget.org/packages/Fantomas/2.3.0.

**Comment by vasily-kirichenko** [comment]
Thanks! Updated.

**Pull request merged**
