### PR TITLE
Always call FSharpChecker async members in ThreadPool

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
This is an attempt to fix UI freezes https://github.com/fsprojects/VisualFSharpPowerTools/issues/958

### CODE REVIEW

**Comment by dungpa** [comment]
I tried the PR and still see some cases UI is frozen. I sent you a PR for those cases.

How do you identify exactly which code fragment is executed on UI thread? We still have a few `StartImmediateSafe` calls left, but fortunately they are invoked directly by users, not executed on cursor changes.

**Comment by dungpa** [comment]
It would be great if we can kill the remaining `StartImmediateSafe` calls:

> Find all "StartImmediateSafe", Match case, Whole word, Find Results 1, Current Project: src\FSharpVSPowerTools.Logic\FSharpVSPowerTools.Logic.fsproj, ""
  C:\PowerTools\src\FSharpVSPowerTools.Logic\VSUtils.fs(349):    static member StartImmediateSafe(computation, ?cancellationToken) =
  C:\PowerTools\src\FSharpVSPowerTools.Logic\ReferenceSourceProvider.fs(35):        |> Async.StartImmediateSafe
  C:\PowerTools\src\FSharpVSPowerTools.Logic\RenameDialog.fs(121):        Async.StartImmediateSafe(
  C:\PowerTools\src\FSharpVSPowerTools.Logic\FindReferencesFilter.fs(122):        } |> Async.StartImmediateSafe
  C:\PowerTools\src\FSharpVSPowerTools.Logic\XmlDocFilter.fs(69):                        |> Async.StartImmediateSafe
  Matching lines: 5    Matching files: 5    Total files searched: 60

**Comment by vasily-kirichenko** [comment]
Still freezes time to time.

**Comment by vasily-kirichenko** [comment]
> How do you identify exactly which code fragment is executed on UI thread?

I created `checker` function in `LanguageService` and forced use the checker via it exclusively. Than set a breakpoint at it and saw what code from which thread tried to obtain the checker.

**Comment by dungpa** [comment]
Do you have "Gray out.." enabled? Maybe this call https://github.com/fsprojects/VisualFSharpPowerTools/blob/9fcdccf7656b7ccac39ead6a0ad7052f73d5f684/src/FSharpVSPowerTools.Logic/SyntaxConstructClassifier.fs#L131-L133 is executed on UI thread?

**Comment by vasily-kirichenko** [comment]
Yes, I have almost all the features enabled. 

I added switching to `ThreadPool` before calling `qualifyOpenDeclarations`. Sill freezes. Maybe it's not a FCS but other our code, like calculating coloring spans?

**Comment by vasily-kirichenko** [comment]
I think it's OK for now.

**Comment by dungpa** [comment]
Is this ready to merge now?

**Comment by vasily-kirichenko** [comment]
Yes.

**Comment by dungpa** [comment]
:shipit:

**Pull request merged**
