### PR TITLE
color function type aliases as reference types

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
Fix for https://github.com/fsprojects/VisualFSharpPowerTools/issues/1126

### CODE REVIEW

**Comment by dungpa** [comment]
@OkayX6 Do you have time to review this :-)?

**Comment by OkayX6** [comment]
Yeah, so the code looks good and I will try the extension :)

**Comment by vasily-kirichenko** [comment]
Maybe it's better to colorize it as Function? Does it make sense?

**Comment by dungpa** [comment]
I think coloring it as a reference type is right.
```fsharp
type Action = unit -> unit
let f : action = failwith ""
```

`Action` is a type, either a reference type or a value type.
`f` is a value of type `Action`; it may be colored as Function.

**Comment by vasily-kirichenko** [comment]
Isn't `f` colored as Function already?

**Comment by dungpa** [comment]
Just checked. Actually no, we haven't checked for function types that are indirect through type alias.

**Comment by vasily-kirichenko** [comment]
OK, I'll fix it now.

**Comment by OkayX6** [comment]
Cool. Other than that the update works well for me.

**Comment by vasily-kirichenko** [comment]
Done. Ready for merging.

**Pull request merged**
