### PR TITLE
fix for "No FSharpSymbolUse for single case union type"

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
wip until https://github.com/fsharp/FSharp.Compiler.Service/issues/301 get merged

### CODE REVIEW

**Comment by dungpa** [comment]
FCS 0.0.85 is available to update.

**Comment by vasily-kirichenko** [comment]
Updated all packages. If tests pass, it's ready for merging. 

I cannot run FSharpVSPowerTools.Tests locally:

```
Не удалось загрузить файл или сборку "Microsoft.VisualStudio.Text.Logic, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" либо одну из их зависимостей. Не удается найти указанный файл.
```
(it says it cannot find that assembly).

**Comment by dungpa** [comment]
Don't know why it's an issue. The dll is always in `lib/vs2012` from early days.

You still need to update the test with new operator tags.

**Comment by vasily-kirichenko** [comment]
done.

**Pull request merged**
