### PR TITLE
Minor updates

### PR DESCRIPTION
**Pull request by dungpa**

### CODE REVIEW

**Comment by dungpa** [comment]
@vasily-kirichenko I added some logging to Generate references for FSI. Please try on your big solutions, we might find a clue why the feature doesn't work on certain solutions.

**Comment by vasily-kirichenko** [comment]
I will try to reproduce the bug with generating references on my solution tomorrow.

**Comment by dungpa** [comment]
@vasily-kirichenko Have you got a relevant log for this?

**Comment by vasily-kirichenko** [comment]
I forget about this :( Will try to reproduce right now.

**Comment by vasily-kirichenko** [comment]
I reproduced it. I added a new reference to a project. Then build it. The output as follows: 
```
[VFPT][Information 01:53:16 PM] Checking projects after build done...
[VFPT][Information 01:53:16 PM] Checking F# project 'p1'...
[VFPT][Information 01:53:16 PM] Checking F# project 'p2'...
[VFPT][Information 01:53:16 PM] Checking F# project 'p3'...
[VFPT][Information 01:53:16 PM] Checking F# project 'p4'...
[VFPT][Information 01:53:16 PM] Checking F# project 'p5'...
[VFPT][Information 01:53:16 PM] Checking F# project 'p6'...
```
Where p1..p6 are projects on which the project I'm building has references. Even if change a code in the project I build, VFPT does not check it.

**Comment by vasily-kirichenko** [comment]
Wait. Actually it checks completely unrelated projects. I mean only p1 is in refs of the project I build. Why does it check them?..

**Comment by vasily-kirichenko** [comment]
Build output is as follows:

`========== Build: 0 succeeded, 0 failed, 3 up-to-date, 0 skipped ==========`

So VS checked only 3 projects, VFPT - 6.

**Comment by dungpa** [comment]
VFPT should check all F# projects in the solution, it doesn't know which projects have been built yet.

So do you mean that your current project is NOT a project from p1 to p6? That is weird.

**Comment by vasily-kirichenko** [comment]
Yes, it does not appear as checked.

**Pull request merged**
