### PR TITLE
use AllowStaleResults.MatchingSource everywhere except RenameCommandFilter

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
Fix for https://github.com/fsprojects/VisualFSharpPowerTools/issues/1016

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
I have no idea why some of the integration tests failed.

**Comment by dungpa** [comment]
What's the goal of this PR? From which feature is the background compile triggered https://github.com/fsprojects/VisualFSharpPowerTools/blob/1b8ccb7de173bd3fe73292bc17b89edd38f0d067/src/FSharpVSPowerTools.Core/LanguageService.fs#L320?

Do you observe any performance improvement with this PR?

A bit of history:

 - We started using `AllowStaleResults.No` for `HighlightUsageTagger` in https://github.com/fsprojects/VisualFSharpPowerTools/pull/502 in order to fix https://github.com/fsprojects/VisualFSharpPowerTools/issues/492
 - We started using `AllowStaleResults.No` for `SyntaxConstructClassifier` at https://github.com/fsprojects/VisualFSharpPowerTools/pull/496

**Comment by dungpa** [comment]
Probably these tests failed because we share the same file names for multiple tests. When `AllowStaleResults.MatchingSource` is used, staled results are reused and consequently wrong results are asserted.

Perhaps creating file names locally to the tests could fix it https://github.com/fsprojects/VisualFSharpPowerTools/blob/1b8ccb7de173bd3fe73292bc17b89edd38f0d067/tests/FSharpVSPowerTools.Tests/HighlightUsageTaggerTests.fs#L47.

**Comment by vasily-kirichenko** [comment]
Yes, selecting text and moving cursor with keyboard seems to work faster with this PR.
Background compile should not be triggered if the file has not been changed, shouldn't it? So, only colorization and renaming should use `AllowStaleResults.No`. 

https://github.com/fsprojects/VisualFSharpPowerTools/issues/492 is not reproduced with this PR.
`SyntaxConstructClassifier` does use `AllowStaleResults.No` in this PR.

> When AllowStaleResults.MatchingSource is used, staled results are reused and consequently wrong results are asserted.

I believe `AllowStaleResults.MatchingSource` allows reuse of results if _file content_ has not been changed, not file name. Am I wrong?

**Comment by dungpa** [comment]
> Background compile should not be triggered if the file has not been changed, shouldn't it? So, only colorization and renaming should use AllowStaleResults.No.

Agreed.

> I believe AllowStaleResults.MatchingSource allows reuse of results if file content has not been changed, not file name. Am I wrong?

You're right. But the integration tests use buffer contents; file names are just placeholders (they don't even exist). I think using unique file names is an OK trade-off.

**Comment by vasily-kirichenko** [comment]
I cannot run tests at home

image

will fix them tomorrow.

**Comment by vasily-kirichenko** [comment]
You are right, generating unique file name for each test solved the problem, except one single test: "should generate highlight usage tags for multi-project symbols". Any ideas?

**Comment by vasily-kirichenko** [comment]
```
FSharpVSPowerTools.Tests.HighlightUsageTaggerTaggerTests.should generate highlight usage tags for multi-project symbols:
  Expected: [(5, 22, 5, 28); (6, 22, 6, 28)]
Actual: []
  Expected and actual are both <Microsoft.FSharp.Collections.FSharpList`1[System.Tuple`4[System.Int32,System.Int32,System.Int32,System.Int32]]>
  Values differ at index [0]
```

**Comment by dungpa** [comment]
That test is a bit subtle. You can write content from https://github.com/fsprojects/VisualFSharpPowerTools/blob/7447e6792ae0ced520842caccbd592f48fce3dd9/tests/FSharpVSPowerTools.Tests/HighlightUsageTaggerTests.fs#L196-L202 to the file before executing. The goal is that its content on disk should be consistent with buffer content https://github.com/fsprojects/VisualFSharpPowerTools/blob/master/tests/data/MultiProjects/Project2/Project21.fs.

Sorry for the inconsistence. It was passing so I never saw it as a bad practice.

**Comment by vasily-kirichenko** [comment]
I added writing the content to the file, but it has not helped. It fails even being run in isolation.

**Comment by dungpa** [comment]
I don't really understand why those multi-project tests are so flaky.

You can ignore it for now. It's too fragile so I always disable it on AppVeyor.

**Comment by vasily-kirichenko** [comment]
OK, so we are waiting for AppVeyor to finish the build.

**Comment by vasily-kirichenko** [comment]
Oops. I've just found that Highlight references does not work nicely in this PR. After renaming it does not re-highlight the symbol. After manual renaming it does not highlight the symbol at all, even after the caret has moved.

**Comment by dungpa** [comment]
Is this the only issue? I think it can be fixed by checking whether the buffer has changed and using `AllowStaleResults.No` instead of `MatchingSource` for such scenarios https://github.com/fsprojects/VisualFSharpPowerTools/blob/07637552a5f2f7aafef29a3fc35149bdb153beee/src/FSharpVSPowerTools.Logic/HighlightUsageTagger.fs#L95.

**Comment by vasily-kirichenko** [comment]
I've tested it with the version before this PR was merged and highlighting after renaming does not work either.

**Comment by vasily-kirichenko** [comment]
It's reproduced on large files in a real solution only. On a two-lines file in a toy solution everything works OK, even on this PR.

**Comment by vasily-kirichenko** [comment]
1. This https://github.com/fsprojects/VisualFSharpPowerTools/blob/07637552a5f2f7aafef29a3fc35149bdb153beee/src/FSharpVSPowerTools.Logic/HighlightUsageTagger.fs#L60 returns None after renaming.

2. This https://github.com/fsprojects/VisualFSharpPowerTools/blob/07637552a5f2f7aafef29a3fc35149bdb153beee/src/FSharpVSPowerTools.Logic/HighlightUsageTagger.fs#L81 is call exactly twice when the caret is moved to a new symbol (including the rename scenario). wtf?

**Pull request merged**
