### PR TITLE
View metadata when Peek Definitions on external assemblies

### LINKED ISSUE #1314: [Peek Definition] should show metadata for external assemblies and C# projects
When I try to peek into another assembly it does nothing.
F12 in contrast shows the fsi window. I think the peek behavior should be consistent with the F12 experience.

### PR DESCRIPTION
**Pull request by dungpa**
Close #1314.

Refactor Navigate to Metadata feature in order to enable Peek Definition.

I haven't tested with VS 2015 so far; just ensure that Go to Definition stills work as is.

@vasily-kirichenko Could you help test Peek Definitions on V S2015 on external assemblies?

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
Add reference to `Microsoft.VisualStudio.Shell.12.0` in VS2015 project.

**Comment by vasily-kirichenko** [comment]
When I press Alt+F12, VS 2015 freezes indefinitely. The UI thread stack trace:

image

If I click on this icon:

image

It unfreezes and the peek definition window appears:

image

Also `System.Guid.fsi` file is open in VS (as a separate normal view). While it's open Alt+F12 works perfectly for `Guid`, once it's closed, the issue is back.

**Comment by dungpa** [comment]
Done. Could you give it a try?

**Comment by vasily-kirichenko** [comment]
Works perfectly.

**Comment by vasily-kirichenko** [comment]
Great job!

**Comment by dungpa** [comment]
Thanks.

**Pull request merged**
