### PR TITLE
Add support to change the tooltip zoom level for outlining

### PR DESCRIPTION
**Pull request by zhengbli**
capture

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
If I enter `0.8` it does not complain, just reset in silently to `0` which is not good. It should highlight the text box in red and / or shows modal dialog if user tries to close settings dialog having invalid zoom level (I believe we do just this for "Navigation bar" setting if VS is running without admin privileges). 

I think it's better to set zoom level in percents, like the editor shows its zoom level:

image

**Comment by vasily-kirichenko** [comment]
On my machine `0,9` is OK, `0.9` is not (it's reset to `0`). So if you are gonna keep supporting decimals, you should parse both formats.

**Comment by vasily-kirichenko** [comment]
Also it should be impossible to enter / save zoom level outside `1%..100%`.

**Comment by zhengbli** [comment]
I changed it accordingly, not it looks more like VS's zoom setting:

**Comment by vasily-kirichenko** [comment]
image

**Comment by zhengbli** [comment]
Hmmm, could it be caching issues? I just uninstalled and reinstalled on my machine, it runs fine.

**Comment by zhengbli** [comment]
I'll try on a new machine on Monday.

**Comment by vasily-kirichenko** [comment]
I deleted `c:\Users\kot\AppData\Local\Microsoft\VisualStudio\12.0Exp` and `c:\Users\kot\AppData\Local\Microsoft\VisualStudio\Exp` - same result.

**Comment by zhengbli** [comment]
oh shoot, it might be that I used nullable int type that breaked vs2013 (I only have 15 installed). Will fix soon

**Pull request merged**
