### PR TITLE
ProjectItem.FileNames use 1 based indexing

### PR DESCRIPTION
**Pull request by enricosada**
0 based index works for compatibility with c#, but raise a Debug.Assert dialog on visualfsharp

ref [MSDN](https://msdn.microsoft.com/en-us/library/envdte.projectitem.filenames.aspx):
> index
Type: System.Int16
Required. The index of file names from 1 to FileCount for the project item.

### CODE REVIEW

**Comment by enricosada** [comment]
there is a better place? an helper class for DTE things? 
i'd like to do add a function `DTE.ProjectItem -> int -> string` with documentation about 1 based indexing instead of inline comment

**Comment by dungpa** [comment]
We have a few extensions methods for `ProjectItem` at https://github.com/fsprojects/VisualFSharpPowerTools/blob/38715049c6c3a5b03478dd19bac47ac2c94a6382/src/FSharpVSPowerTools.Logic/VSUtils.fs#L180-L197.

**Comment by enricosada** [comment]
extracted function VSUtils.filePath

**Comment by dungpa** [comment]
:+1:

**Pull request merged**
