### PR TITLE
Support F# 4.0 constructs

### LINKED ISSUE #1046: Support F# 4.0 constructs
Visual Studio 2015 is close to RTM. We should migrate to a FCS version that is compatible with F# 4.0. 

The relevant FCS version is available at https://www.nuget.org/packages/FSharp.Compiler.Service/1.4.0-beta.

### PR DESCRIPTION
**Pull request by dungpa**
Close #1046.

I have done initial migration.
Please help test it with a VS 2015 installation.

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
I don't have vs 2015 installed anywhere.

**Comment by dungpa** [comment]
Isn't it time to install VS 2015 :-P? 

I usually use Azure VMs to test things out. They're really handy http://blogs.msdn.com/b/visualstudio/archive/2015/01/08/azure-virtual-machine-images-for-visual-studio.aspx.

**Comment by vasily-kirichenko** [comment]
My machine is broken after some of vs 2015 ctp, so rtm refuses to install. Will reinstall windows. But not now. 

I tried vs in azure and it was a painful experience due to performance.

**Comment by dungpa** [comment]
Migration is done. The PR can be merged after further testing.

**Comment by vasily-kirichenko** [comment]
I suggest to merge it and create a special beta package and ask people to test it. After fixing bugs, we can release it normally.

**Comment by dungpa** [comment]
Announced on Twitter https://twitter.com/FSPowerTools/status/623389014243045376

Publishing a beta package is not a good idea since it produces crashes for everyone. My aim is to protect against all obvious crashes and publish a new release. Any real fix would require patching FCS first.

**Comment by dungpa** [comment]
Fixed all issues that I knew. 

We can merge this PR. Any further updates can be done via new PRs.

**Comment by vasily-kirichenko** [comment]
I have not a chance to test it at work. On toy projects it works ok (except Ctrl+, does not work, of course).

**Comment by dungpa** [comment]
Please try with bigger solutions when you have a chance. It's quite usable; just need to test on more extensive loads.

**Pull request merged**
