### PR TITLE
Generate lightweight interfaces.

### LINKED ISSUE #1086: Lightweight interface implementation
Currently if you have VFPT implement an interface, you get a fully-typed, verbose implementation e.g.

```fsharp
let processor = {
    new IEventProcessor with
        member __.CloseAsync(context: PartitionContext, reason: CloseReason): System.Threading.Tasks.Task = 
            failwith "Not implemented yet"
        
        member __.OpenAsync(context: PartitionContext): System.Threading.Tasks.Task = 
            failwith "Not implemented yet"
        
        member __.ProcessEventsAsync(context: PartitionContext, messages: System.Collections.Generic.IEnumerable<EventData>): System.Threading.Tasks.Task = 
            failwith "Not implemented yet"
}
```

I will almost always simplify the above to: -

```fsharp
let processor = {
    new IEventProcessor with
        member __.CloseAsync(context, reason) = failwith "Not implemented yet"        
        member __.OpenAsync context = failwith "Not implemented yet"        
        member __.ProcessEventsAsync(context, messages) = failwith "Not implemented yet"
    }
```

I know that might not be everyone's cup of tea, but an option to have this would be nice. Even a halfway house that didn't use fully-qualified namespaces but added open statements would be good.

### PR DESCRIPTION
**Pull request by isaacabraham**
Fixes #1086. Please review - I've done some basic testing and it seems to work ok, but I'm sure I've missed a few things out somewhere.

### CODE REVIEW

**Comment by isaacabraham** [comment]
Didn't realise there were actually unit tests around this :-) Will fix tomorrow.

**Comment by isaacabraham** [comment]
Weird. I can't get any test runner to actually run those tests within VS - have tried both the VS test runner with the NUnit extension and Code Rush - neither of them identify the tests in the .Tests project.

**Comment by vasily-kirichenko** [comment]
Nunit.exe

**Comment by dungpa** [comment]
I can run tests using VS test runner or TestDriven.Net test runner.

Most of failing tests are from https://github.com/fsprojects/VisualFSharpPowerTools/blob/master/tests/FSharpVSPowerTools.Tests/ImplementInterfaceSmartTaggerTests.fs. It occurs because you change the default path to use lightweight interface implementation https://github.com/fsprojects/VisualFSharpPowerTools/blob/e736aa38668d182696b04dd2f6e6dd637b2515f1/tests/FSharpVSPowerTools.Tests/ImplementInterfaceSmartTaggerTests.fs#L94.

**Comment by isaacabraham** [comment]
This is probably still failing because I don't still put in extra line breaks like we used to. Can one of you run with this to get it passing - I can't get the tests running here.

**Comment by vasily-kirichenko** [comment]
I have not managed to run those tests for a year or so.

**Comment by dungpa** [comment]
@isaacabraham Could you give it a last try? The failing tests and their reasons are always available at build logs https://ci.appveyor.com/project/dungpa/visualfsharppowertools/build/2.1.0-a1508221847#L2604.

**Comment by dungpa** [comment]
@isaacabraham Great jobs. 

I merged the PR and fixed the remaining tests.
I fixed test execution on master so it should be easy to run VS unit tests from now on.

**Comment by isaacabraham** [comment]
Sorry didn't have a chance to fix the last tests. Thanks for sorting!

**Pull request merged**
